server:
  port: 8099
spring:
  application:
    name: 数据配置中心
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    cache: false
    encoding: utf-8
    check-template-location: false
    enabled: true
    prefix: classpath:/templates/

  datasource:
    username: root
    password: Passw0rd
    url: jdbc:mysql://localhost:3306/procurement_statistics?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

#logging:
#  config: classpath:config/logback.xml
#  level:
#    com.zfcg.datadisplay.zfcg.mapper: DEBUG
