server:
  protocol: http
  address: 127.0.0.1
  port: 8089
spring:
  application:
    name: 数据配置中心
  resources:
    static-locations: classpath:/static/
  mvc:
    view:
      prefix: /
      suffix: .html

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    username: root
#    password: Passw0rd
#    url: jdbc:mysql://localhost:3306/procurement_statistics?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    url: jdbc:mysql://192.168.1.201:21563/scsme-daav?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: df34SD#4s
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 2
    min-idle: 1
    max-wait: 60000
    max-active: 10
    time-between-eviction-runs-millis: 30000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    filters: stat
    break-after-acquire-failure: true
    connection-error-retry-attempts: 3
    validation-query: SELECT 1
  ## 设定 flyway 属性
  flyway:
    # 启用或禁用 flyway
    enabled: true
    # flyway 的 clean 命令会删除指定 schema 下的所有 table, 杀伤力太大了, 应该禁掉.
    clean-disabled: true #禁用clean操作
    baseline-on-migrate: true #初始化时如果不存在迁移记录表，默认新建一个
    out-of-order: false #防止开发环境下漏掉没来得及apply的文件，产品环境最好设为false
    locations: classpath:/db/migration
#logging:
#  config: classpath:config/logback.xml
#  level:
#    com.zfcg.datadisplay.zfcg.mapper: DEBUG

  freemarker:
    template-loader-path: classpath:/templates/freemarker/
    #关闭缓存，及时刷新，上线生产环境需要修改为true
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    suffix: .ftl
  mail:
    host: smtp.163.com
    port: 25
    username: xuelangice
    fromAddress: xuelangice@163.com
    password: 182414
    nickname:

    properties:
      smtp:
        starttls:
          enable: true
          required: true
        auth: true
      mail:
        smtp:
          ssl:
            enable: false

  ldap:
    urls:
    username:
    password:
    base:
    domainName:    # domainName 指 企业邮箱后缀，如企业邮箱为：xxx@example.com, 这里值为 '@example.com'

  security:
    user:
      name: user
      password: 123
    basic:
      enabled: false
    management:
      security:
        enabled: false
    oauth2:
      enable: false
  ## redis config
  ## please choose either of the two ways
  redis:
    isEnable: false

    ## standalone config
    host: 127.0.0.1
    port: 6379

    ## cluster config
    #  cluster:
    #       nodes:

    password:
    database: 0
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
  devtools:
    restart:
      enabled: true
springfox:
  documentation:
    swagger:
      v2:
        path: /api-doc


pagehelper:
  supportMethodsArguments: true
  reasonable: true
  returnPageInfo: check
  helperDialect: mysql
  params: count=countSql

mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.scsme.dataConfigCenter.davinci.biz.model
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

#逻辑删除的状态
#mybatis-plus:
#  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
#  type-aliases-package: com.scsme.dataConfigCenter.mapper
#  global-config:
#    db-config:
#      logic-delete-value: 1
#      logic-not-delete-value: 0

mapper:
  identity: MYSQL
  not-empty: false
  mappers: com.scsme.dataConfigCenter.davinci.biz.dao

sql_template_delimiter: $
custom-datasource-driver-path: ${DAVINCI3_HOME}/config/datasource_driver.yml

DAVINCI3_HOME: E:/home/davinci
file:
  userfiles-path: ${DAVINCI3_HOME}/userfiles/
  web_resources: ${DAVINCI3_HOME}/davinci-ui/
  phantomJs-path: ${DAVINCI3_HOME}/bin/phantom.js
  base-path: ${DAVINCI3_HOME}/lib/
## jwt is one of the important configuration of the application
## jwt config cannot be null or empty
jwtToken:
  secret: secret
  timeout: 1800000
  algorithm: HS512
